name: CI
on: [push]
jobs:

  check:
    name: Check Format on Ubuntu latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Node Packages
      run: yarn
    - name: Run eslint command
      run: yarn eslint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies and build
        run: yarn && yarn build
      - name: Run tests
        run: yarn test
