name: CI
on: [push]
jobs:

  check:
    name: Check Format on Ubuntu latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Node Packages
      run: yarn
    - name: Run eslint command
      run: yarn eslint

  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies and build
        run: yarn && yarn build
      # - name: Install and run Lighthouse CI
      #   run: |
      #     yarn global add @lhci/cli@0.10.x
      #     lhci autorun
      #   env:
      #     LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
